11.0 l10n es extra data
factorlibre/l10n-spain pull request #24
Opened 2022-08-03 11:09 UTC by OscarIndias

https://git.factorlibre.com/odoo-11/starterp-basic-db-v11/-/issues/290

2022-08-03 14:48 UTC, ljsalvatierra-factorlibre requested changes

2022-08-03 14:48 UTC, ljsalvatierra-factorlibre commented on l10n_es_extra_data/__manifest__.py
> +    "version": "11.0.1.0.1",
Pondría de inicio la versión `11.0.1.0.0`.

2022-08-09 11:04 UTC, OscarIndias commented
Se ha hecho el cambio en la descripción de las plantillas de los impuestos

2022-08-09 12:33 UTC, ljsalvatierra-factorlibre approved these changes

2022-08-12 10:43 UTC, merged